env:
  es2021: true
  node: true
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: 5
globals:
  _: readonly
  console: readonly
rules:
  array-bracket-spacing:
    - error
    - never
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  curly:
    - error
    - all
  comma-dangle:
    - error
    - always-multiline
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  object-curly-spacing:
    - error
    - always
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - error
    - always
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
  space-before-blocks:
    - error
    - always
  space-infix-ops:
    - error
