name: CI
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ 'ruby:2.5', 'ruby:2.6', 'ruby:2.7' ]
    container:
      image: ${{ matrix.image }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup bundler
      run: gem install bundler
    
    - name: bundle install
      run: bundle install --jobs=4 --retry=3 --path=./vendor
      
    - name: Show versions
      run: |
        ruby --version
        bundle --version

    - name: test
      run: bundle exec rake spec
