name: Lint CloudFormation Templates

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Workflow dispatch trigger allows manually running workflow
  workflow_dispatch: {}

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.2

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cfn-lint -t ./cost/aws/FlexeraReadOnlyPolicy.template
