name: Generate Meta Parent Policy Templates

on:
  # Trigger this workflow on pushes to master
  push:
    branches:
      - master
      - feat/bk_meta_parent_policy_compiler # For Dev Only. Remove before merging to master

  # Workflow dispatch trigger allows manually running workflow
  workflow_dispatch:
    branches:
      - master

jobs:
  meta-parent-policy-templates:
    name: "Generate Meta Parent Policy Templates"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Speed up checkout by not fetching history

      - uses: ruby/setup-ruby@v1

      - name: Generate Meta Parent Policy Template
        working-directory: tools/meta_parent_policy_compiler
        run: |
          for child_pt in ../../cost/azure/unused_volumes/azure_unused_volumes.pt ../../cost/aws/idle_compute_instances/idle_compute_instances.pt ../../cost/aws/object_storage_optimization/aws_object_storage_optimization.pt ../../cost/aws/old_snapshots/aws_delete_old_snapshots.pt ../../cost/aws/rightsize_compute_instances/aws_compute_rightsizing.pt ../../cost/aws/rightsize_ebs_volumes/aws_volumes_rightsizing.pt ../../cost/aws/unused_ip_addresses/aws_unused_ip_addresses.pt ../../cost/aws/unused_rds/unused_rds.pt ../../cost/aws/unused_volumes/aws_delete_unused_volumes.pt; do
            ruby meta_parent_policy_compiler.rb $child_pt;
          done

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update Meta Parent Policy Templates"
          title: "Update Meta Parent Policy Templates"
          body: "Update Meta Parent Policy Templates from GitHub Actions Workflow [${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          branch: "task/update-meta-parent-policy-templates"
          delete-branch: true
          labels: "automation"

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
