name: Generate Policy API List

permissions:
  contents: write
  pull-requests: write

on:
  # Trigger this workflow on pushes to master
  push:
    branches:
      - master

  # Workflow dispatch trigger allows manually running workflow
  workflow_dispatch: {}

jobs:
  policy-api-list:
    name: "Generate Policy API List"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Speed up checkout by not fetching history

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate Policy API List
        working-directory: tools/policy_api_list_generation
        run: |
          python3 policy_api_list_generator.py

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update Policy API List"
          title: "Update Policy API List"
          body: "Update Policy API List from GitHub Actions Workflow [${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          branch: "task/update-policy-api-list"
          delete-branch: true
          labels: "automation"

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
