name: Generate Repository README File

permissions:
  contents: write
  pull-requests: write

on:
  # Trigger this workflow on pushes to master
  push:
    branches:
      - master

  # Workflow dispatch trigger allows manually running workflow
  workflow_dispatch: {}

jobs:
  generate_readme:
    name: "Generate Repository README File"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Speed up checkout by not fetching history

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          # ruby-version: 2.4.1 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install Ruby libraries
        shell: bash -l {0} # https://github.com/actions/virtual-environments/issues/4
        run: bundle install --without documentation --path bundle

      - name: Run Repository README File Script
        shell: bash -l {0} # https://github.com/actions/virtual-environments/issues/4
        run: |
          ruby tools/readme_policy_table_of_contents/generate_readme_policy_table_of_contents.rb

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update Generate Repository README File"
          title: "Update Generate Repository README File"
          body: "Updated Generate Repository README File from GitHub Actions Workflow [${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          branch: "task/update-repository-readme"
          delete-branch: true
          labels: "automation, readme"

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
