name: Generate Policy Release Notifications

permissions:
  contents: read

on:
  # Trigger this workflow on pushes to master that affect policy templates
  push:
    branches:
      - master
    paths:
      - '**/*.pt'

  # Workflow dispatch trigger allows manually running workflow
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  policy-release-notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full git history (required for release notification generation)

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Send Teams Notification
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.POLICY_CATALOG_UPDATE_TEAMS_WEBHOOK_URL_PROD }}
        run: |
          ruby tools/policy_template_release_generation/generate_policy_release_notification_contents.rb
