name: Generate AWS EC2 Instance Types JSON

on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    # At 06:00 UTC on Sundays
    - cron: "0 6 * * 0"

  # Workflow dispatch trigger allows manually running workflow
  workflow_dispatch: {}

jobs:
  aws_ec2_instance_types:
    name: "Generate AWS EC2 Instance Types"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Speed up checkout by not fetching history

      - uses: actions/setup-python@v5
        with:
          python-version: 3.10.12
          cache: 'pip' # caching pip dependencies

      - run: pip install -r requirements.txt

      - run: python3 tools/cloud_data/aws/aws_instance_types.py

      - name: Generate AWS EC2 Instance Types List
        shell: bash -l {0} # https://github.com/actions/virtual-environments/issues/4
        run: python3 tools/cloud_data/aws/aws_instance_types.py
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update AWS EC2 Instance Types Data"
          title: "Update AWS EC2 Instance Types Data"
          body: "Updated AWS EC2 Instance Types from GitHub Actions Workflow [${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          branch: "task/update-aws-ec2-instance-types"
          delete-branch: true
          labels: "automation, data, aws"

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
