name: Generate Azure Pricing JSON

on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    # At 00:00 UTC on Sundays
    - cron: "0 0 * * 0"

  # Workflow dispatch trigger allows manually running workflow
  workflow_dispatch: {}

jobs:
  azure_vm_pricing:
    name: "Generate Azure VM Pricing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Speed up checkout by not fetching history

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip' # Cache pip dependencies to speed up workflow runs

      - working-directory: data/azure/
        run: pip install -r requirements.txt

      - working-directory: data/azure/
        run: |
          python azure_vm_pricing.py

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
