name: Generate GCP VM Pricing JSON

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    # At 02:00 UTC on Sundays
    - cron: "30 4 * * 0"

  # Workflow dispatch trigger allows manually running workflow
  workflow_dispatch: {}

jobs:
  gcp_compute_instance_types:
    name: "Generate GCP VM Pricing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Speed up checkout by not fetching history

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13.2
          cache: 'pip' # caching pip dependencies

      - run: pip install -r requirements.txt

      - name: Make local JSON file containing Google auth information
        shell: bash -l {0} # https://github.com/actions/virtual-environments/issues/4
        run: |
          mkdir -p tmp
          python3 tools/cloud_data/google/google_make_credential_json.py
        env:
          GOOGLE_AUTH_JSON: ${{ secrets.GOOGLE_AUTH_JSON }}
          GOOGLE_APPLICATION_CREDENTIALS: "tmp/gcp_credential.json"

      - name: Generate GCP Compute Instance Types List
        shell: bash -l {0} # https://github.com/actions/virtual-environments/issues/4
        run: python3 tools/cloud_data/google/google_vm_pricing.py
        env:
          GOOGLE_AUTH_JSON: ${{ secrets.GOOGLE_AUTH_JSON }}
          GOOGLE_APPLICATION_CREDENTIALS: "tmp/gcp_credential.json"

      - name: Delete local JSON file containing Google auth information
        shell: bash -l {0} # https://github.com/actions/virtual-environments/issues/4
        run: rm tmp/gcp_credential.json

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update GCP VM Pricing Data"
          title: "Update GCP VM Pricing Data"
          body: "Updated GCP VM Pricing from GitHub Actions Workflow [${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          branch: "task/update-gcp-vm-pricing"
          delete-branch: true
          labels: "automation, data, gcp"

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
