name: Generate Master Policy Permissions JSON 

on:
  # Trigger this workflow on pushes to master
  push:
    branches:
      - master
      - POL-918-create-master-policy-perm-list


  # Workflow dispatch trigger allows manually running workflow
  workflow_dispatch:
    branches:
      - master
      - POL-918-create-master-policy-perm-list


jobs:
  master-policy-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Speed up checkout by not fetching history

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Run Generate Master Policy Permissions Script
        id: policy_permissions_json
        run: |
          ruby tools/policy_master_permission_generation/generate_master_policy_permissions.rb
          
        # cp dist/master_policy_permissions_list.json data/policy_permissions_list
