name: Create EU_Policies promotion pull request
on:
  push:
    branches:
      - master
jobs:
  EU_PoliciesPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: EU_Policies
      - name: Merge in main
        run: |
          git fetch origin master:master
          git merge master --strategy-option theirs
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: EU_Policies
          branch: master
          branch-suffix: random
          delete-branch: true
          draft: true
          run: |
            echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
            echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
