name: Create EU_Policies promotion pull request
on:
  push:
    branches:
      - master
jobs:
  EU_PoliciesPromotion:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: EU_Policies
          branch: master
