name: Update Change History

on:
  # Trigger this workflow on pushes to master
  push:
    branches:
      - master

  # Workflow dispatch trigger allows manually running workflow
  workflow_dispatch:
    branches:
      - master

jobs:
  change-history:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Speed up checkout by not fetching history

      - name: Configure Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run Generate Change History Script
        id: generate_change_history
        run: |
          ruby tools/change_history/generate_change_history.rb
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update Change History"
          title: "Update Change History"
          body: "Update Change History from GitHub Actions Workflow [${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          branch: "task/update-change-history"
          delete-branch: true
          labels: "automation"

      - name: Check Outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
